theme: jekyll-theme-minimal
title: Rachel Gray
description: Gravitational-wave astronomer and lecturer at the University of Glasgow 
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
  - title: CV
    url: cv

