theme: jekyll-theme-minimal
title: Rachel Gray
description: Personal website
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
  - title: CV
    url: cv
  - title: Contact
    url: contact
